In [1]:
import pandas as pd

In [3]:
path = r'C:\Users\sebastian sossa\Documents\integraIT\projects_integrait\DNDI\data\ReportUAT.csv'
df_root = pd.read_csv(path, delimiter=';')

In [4]:
df_root

,Id Form,idCampo,Site,Visit,name,NameActividad,activityState,fecha enrolado,Participante,Estado del Participante,...,Valor,displayName,id option,Variable,visible,required,TipoDato,TypeQuery,MessageQuery,QueryState
0,1,2,"01 PECET/Clinica CES. Medellin, Colombia",Screening Visit,Date of visit,Date of visit,DATA_ENTRY_COMPLETE,27/09/2023 14:36,11001,DROPOUT,...,\N,\N,\N,SVREASND,0,1,TEXT,\N,\N,\N
1,1,3,"01 PECET/Clinica CES. Medellin, Colombia",Screening Visit,Date of visit,Date of visit,DATA_ENTRY_COMPLETE,27/09/2023 14:36,11001,DROPOUT,...,30-sep-23,\N,\N,SVDAT,1,1,DATE,AUTOQUERY,Date must not be in the future,OPEN
2,2,5,"01 PECET/Clinica CES. Medellin, Colombia",Screening Visit,Informed Consent,Informed Consent,DATA_ENTRY_COMPLETE,27/09/2023 14:36,11001,DROPOUT,...,27-sep-23,\N,\N,RFICDAT,\N,1,DATE,\N,\N,\N
3,2,8,"01 PECET/Clinica CES. Medellin, Colombia",Screening Visit,Informed Consent,Informed Consent,DATA_ENTRY_COMPLETE,27/09/2023 14:36,11001,DROPOUT,...,S002,\N,\N,ICSCRNUM,1,1,TEXT,\N,\N,\N
4,3,10,"01 PECET/Clinica CES. Medellin, Colombia",Screening Visit,Demographics,Demographics,DATA_ENTRY_COMPLETE,27/09/2023 14:36,11001,DROPOUT,...,1991,\N,\N,BRTHYY,\N,1,NUMBER,\N,\N,\N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,27,489,"01 PECET/Clinica CES. Medellin, Colombia",D7,Vital Signs,Vital Signs,DATA_ENTRY_COMPLETE,27/09/2023 14:36,11001,DROPOUT,...,1,Normal,697,VSUNRESPINTP,1,1,OPTIONS,AUTOQUERY,The Respiratory rate is not within expected ra...,OPEN
1208,27,492,"01 PECET/Clinica CES. Medellin, Colombia",D7,Vital Signs,Vital Signs,DATA_ENTRY_COMPLETE,27/09/2023 14:36,11001,DROPOUT,...,1,Normal,701,VSUNTEMPINTP,1,1,OPTIONS,AUTOQUERY,The Oral Temperature is not within expected ra...,OPEN
1209,29,710,"01 PECET/Clinica CES. Medellin, Colombia",D7,Injection Site Examination,Injection Site Examination,DATA_ENTRY_COMPLETE,27/09/2023 14:36,11001,DROPOUT,...,0,No,912,EXINJSTAT,\N,1,OPTIONS,\N,\N,\N
1210,30,778,"01 PECET/Clinica CES. Medellin, Colombia",D7,PBMC Isolate,PBMC Isolate,DATA_ENTRY_COMPLETE,27/09/2023 14:36,11001,DROPOUT,...,1,Yes,1063,LBPBMCSTAT,\N,1,OPTIONS,\N,\N,\N
1211,40,826,"01 PECET/Clinica CES. Medellin, Colombia",D7,Pharmacodynamic Blood Sampling (PD) -Cytokines...,Pharmacodynamic Blood Sampling (PD) -Cytokines...,DATA_ENTRY_COMPLETE,27/09/2023 14:36,11001,DROPOUT,...,1,Yes,1137,LBPDSTAT,\N,1,OPTIONS,\N,\N,\N

In [12]:
df_root[['Visit', 'name', 'Campo', 'Valor']]

,Visit,name,Campo,Valor
0,D-1,Date of visit,Was the visit performed?,1
1,D-1,Date of visit,Was the visit performed?,1
2,D-1,Date of visit,Was the visit performed?,1
3,D-1,Date of visit,Was the visit performed?,1
4,D-1,Date of visit,Was the visit performed?,1
...,...,...,...,...
55720,D1,mRNA Markers,"12-hours post dose, Reason not done",Randomly answered
55721,D1,mRNA Markers,"12-hours post dose, Reason not done",Randomly answered
55722,D15,mRNA Markers,"12-hours post dose, Reason not done",time
55723,D15,mRNA Markers,"12-hours post dose, Reason not done",Randomly answered
55724,D29,mRNA Markers,"12-hours post dose, Reason not done",Randomly answered

In [9]:
df_root.activityState.unique()

array(['DATA_ENTRY_COMPLETE', 'DATA_ENTRY_INCOMPLETE'], dtype=object)

In [8]:
df_root.identifierPrefix

0        1
1        1
2        1
3        1
4        1
        ..
55720    1
55721    1
55722    1
55723    1
55724    1
Name: identifierPrefix, Length: 55725, dtype: int64

In [3]:
df_root.name.unique()

array(['Date of visit', 'Informed Consent', 'Demographics',
       'Child Bearing Potential', 'History of cutaneous leishmaniasis',
       'Covid 19 testing', 'Eligibility',
       'Medical Or Surgical History (other than Leishmaniasis)',
       'Vein assessment', 'Urinary Drug Screen', 'Alcohol Screen',
       'Pregnancy Test', 'Clinical Laboratory - Test Hematology',
       'Clinical Laboratory Test - Clinical Chemistry',
       'Clinical Laboratory Test - Clinical Chemistry D-1',
       'Clinical Laboratory Test - Coagulation',
       'Immunoassay (Thyroid Stimulating Hormone)', 'Urinalysis',
       'Urine Microscopic Examination', 'Virology', 'Lesion Measurement',
       'Interleukin-6', 'Titration Of Auto-Antibodies',
       'Physical Examination', 'Vital Signs', '12-Lead ECG',
       'Injection Site Examination', 'PBMC Isolate',
       'Pharmacokinetic Blood Sampling (PK)',
       'Pharmacodynamic Blood Sampling (PD) -Cytokines/Chemokines',
       'mRNA Markers'], dtype=object)

In [5]:
df = df_root[df_root['name']=='Date of visit']
lista_sujetos = df['Participante'].unique()
df = df[['name', 'Visit', 'activityState', 'Participante', 'Estado del Participante', 'Campo', 'Valor']]

In [6]:
df

,name,Visit,activityState,Participante,Estado del Participante,Campo,Valor
0,Date of visit,Screening Visit,DATA_ENTRY_COMPLETE,11001,DROPOUT,Provide the reason,\N
1,Date of visit,Screening Visit,DATA_ENTRY_COMPLETE,11001,DROPOUT,Visit Date,30-sep-23
197,Date of visit,D-1,DATA_ENTRY_COMPLETE,11001,DROPOUT,Provide the reason,\N
198,Date of visit,D-1,DATA_ENTRY_COMPLETE,11001,DROPOUT,Visit Date,29-sep-23
414,Date of visit,D1,DATA_ENTRY_COMPLETE,11001,DROPOUT,Provide the reason,\N
415,Date of visit,D1,DATA_ENTRY_COMPLETE,11001,DROPOUT,Visit Date,27-sep-23
525,Date of visit,D2,DATA_ENTRY_COMPLETE,11001,DROPOUT,Provide the reason,\N
526,Date of visit,D2,DATA_ENTRY_COMPLETE,11001,DROPOUT,Visit Date,1-sep-23
646,Date of visit,D3,DATA_ENTRY_COMPLETE,11001,DROPOUT,Provide the reason,\N
647,Date of visit,D3,DATA_ENTRY_COMPLETE,11001,DROPOUT,Visit Date,27-sep-23
745,Date of visit,D4,DATA_ENTRY_COMPLETE,11001,DROPOUT,Provide the reason,No se presento
746,Date of visit,D4,DATA_ENTRY_COMPLETE,11001,DROPOUT,Visit Date,\N
747,Date of visit,D7,DATA_ENTRY_COMPLETE,11001,DROPOUT,Provide the reason,\N
748,Date of visit,D7,DATA_ENTRY_COMPLETE,11001,DROPOUT,Visit Date,26-sep-23
865,Date of visit,Screening Visit,DATA_ENTRY_COMPLETE,11001,DROPOUT,Was the visit performed?,1
975,Date of visit,D-1,DATA_ENTRY_COMPLETE,11001,DROPOUT,Was the visit performed?,1
1084,Date of visit,D1,DATA_ENTRY_COMPLETE,11001,DROPOUT,Was the visit performed?,1
1106,Date of visit,D2,DATA_ENTRY_COMPLETE,11001,DROPOUT,Was the visit performed?,1
1125,Date of visit,D3,DATA_ENTRY_COMPLETE,11001,DROPOUT,Was the visit performed?,1
1152,Date of visit,D4,DATA_ENTRY_COMPLETE,11001,DROPOUT,Was the visit performed?,0
1153,Date of visit,D7,DATA_ENTRY_COMPLETE,11001,DROPOUT,Was the visit performed?,1

In [5]:
df = df[df['Participante']=='012009']

In [7]:
df = df[df['Visit']=='D30']

In [5]:
df.activityState.unique()

array(['DATA_ENTRY_COMPLETE', 'DATA_ENTRY_INCOMPLETE', 'DATA_EMPTY'],
      dtype=object)

In [33]:
df_informed = df_root[df_root['name']=='Informed Consent']
df_informed = df_informed[['Visit','Participante', 'Campo', 'Valor']]
df_informed = df_informed[df_informed['Campo']=='Informed consent signature date']
df_informed = df_informed[['Visit','Participante','Valor']]
df_informed = df_informed.rename(columns={'Participante':'Subject'})

In [28]:
# pru_1 = df[df['Participante']=='011002']
# pru_1 = pru_1[pru_1['Visit']=='D1']
# pru = pru_1
# pru = pru[['Campo', 'Valor']].T
# new_columns = pru.iloc[0]
# pru = pru[1:].set_axis(new_columns, axis=1)
# pru['Subject'] = pru_1['Participante'].unique()
# pru['Visit'] = pru_1['Visit'].unique()
# pru['state'] = pru_1['activityState'].unique()
# pru

In [38]:
from datetime import datetime
from revision_fechas import revision_fecha
import warnings

warnings.filterwarnings('ignore')

lista_revision = []

# fecha_inicio = datetime.strptime('19-06-2023', "%d-%m-%Y")
# fecha_fin =  datetime.strptime('31-10-2023', "%d-%m-%Y")

for sujeto in lista_sujetos:
    sujeto_principal = df[df['Participante']==sujeto]

    visit_dictionary = {'Screening Visit': '', 'D-1':'', 'D1':'', 'D2':'', 'D3':'', 'D4':'', 'D7':'', 'D14':'', 
    'D15':'', 'D16':'', 'D17':'', 'D18':'', 'D21':'', 'D28':'', 'D29':'', 'D30':'',
    'D31':'', 'D32':'', 'D35':'', 'D42':'', 'D63':'', 'D90':'', 'D105':''}

    for visita in sujeto_principal.Visit.unique():
     
        pru_1 = sujeto_principal[sujeto_principal['Visit']==visita]
        pru = pru_1
        pru = pru[['Campo', 'Valor']].T
        new_columns = pru.iloc[0]
        pru = pru[1:].set_axis(new_columns, axis=1)
        pru['Subject'] = sujeto
        pru['Visit'] = visita
        pru['status'] = pru_1['activityState'].unique()

        pru = pru.merge(df_informed, on=['Subject', 'Visit'], how='left')
        

        for index, row in pru.iterrows():
            status = row['status']
            try:
                was_performed = row['Was the visit performed?']
            except:
                pass
            provide_reason = row['Provide the reason']
            visit_date = row['Visit Date']
            subject = row['Subject']
            visit = row['Visit']
            informed_consent_date = row['Valor']

            
            
            if status == 'INCOMPLETE' or status == 'PENDING_QUERIES':
                pass
            else:
                
                # Primera  revision general de formato de fecha ->GE0020
                f = revision_fecha(visit_date)
                if f == None:
                    pass
                else:
                    error = [subject, visit, f , visit_date, 'GE0020']
                    lista_revision.append(error)         

                # Agregamos la fecha de visit date al diccionario, para poder ser consultado posteriormente
                visit_dictionary[visit] = visit_date
                
                try:
                    # Verificamos si la fecha de la visita es mayor o igual al inofrm consent date -> VS0050
                    if datetime.strptime(str(visit_date), '%d-%b-%Y') >= datetime.strptime(str(informed_consent_date), '%d-%b-%Y'):
                        pass
                    else:
                        error = [subject, visit, 'Visit date must be equal or greater than the inform consent date', visit_date, 'VS0050']
                        lista_revision.append(error)
                except:
                    pass

    
    # Codigo para verificar si las fechas de las visitas, son mayores consecutivamente -> VS0020
    lista_valores_diccionario_visitas = list(visit_dictionary.values())
    lista_keys_diccionario_visitas = list(visit_dictionary.keys())

    for i in range(len(lista_valores_diccionario_visitas)):

        if  lista_valores_diccionario_visitas[i] == 0:
            pass
        elif lista_valores_diccionario_visitas[i] == '' :
            break

        elif lista_valores_diccionario_visitas[i] == 'D-1' :
                if datetime.strptime(lista_valores_diccionario_visitas[i], '%d-%b-%Y')  < datetime.strptime(lista_valores_diccionario_visitas[i-1], '%d-%b-%Y'):
                    error = [sujeto, lista_keys_diccionario_visitas[i], 'Visit date must be greater than the previous visit date' , lista_valores_diccionario_visitas[i], 'VS0020']
                    lista_revision.append(error)
                else:
                    pass
            

        else:
            try:
                if datetime.strptime(lista_valores_diccionario_visitas[i], '%d-%b-%Y')  <= datetime.strptime(lista_valores_diccionario_visitas[i-1], '%d-%b-%Y'):
                    error = [sujeto, lista_keys_diccionario_visitas[i], 'Visit date must be greater than the previous visit date' , lista_valores_diccionario_visitas[i], 'VS0020']
                    lista_revision.append(error)
                else:
                    pass
            except:
                pass